version: '3.8'
services:

  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_URI: postgres://authenticator:${PGRST_DB_AUTH_PASSWORD}@db:5432/gw2index
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: gw2index
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGRST_DB_AUTH_PASSWORD: ${PGRST_DB_AUTH_PASSWORD}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/